CREATE TABLE `ukDailyForecast` (
	`forecastID` INT NOT NULL AUTO_INCREMENT,
	`forecastDate` VARCHAR( 30 ) NOT NULL,
	`issueDate` INT (2) NOT NULL,
	`issueMonth` INT (2) NOT NULL,
	`issueYear` INT (4) NOT NULL,
	`issueTime` INT (4) NOT NULL,
	`headline` VARCHAR (500) NOT NULL,
	`synopsis` TEXT (4000) NOT NULL,
	`maxTempC` INT (3) NOT NULL,
	`minTempC` INT (3) NOT NULL,
	`pollen` INT (2) NOT NULL,
	`uv` INT (2) NOT NULL,
	`scillyTempC` INT (3) NOT NULL,
	`plymouthTempC` INT (3) NOT NULL,
	`southamptonTempC` INT (3) NOT NULL,
	`londonTempC` INT (3) NOT NULL,
	`norwichTempC` INT (3) NOT NULL,
	`birminghamTempC` INT (3) NOT NULL,
	`aberystywhtTempC` INT (3) NOT NULL,
	`manchesterTempC` INT (3) NOT NULL,
	`yorkTempC` INT (3) NOT NULL,
	`newcastleTempC` INT (3) NOT NULL,
	`isleOfManTempC` INT (3) NOT NULL,
	`carlisleTempC` INT (3) NOT NULL,
	`edinburghTempC` INT (3) NOT NULL,
	`glasgowTempC` INT (3) NOT NULL,
	`aberdeenTempC` INT (3) NOT NULL,
	`invernessTempC` INT (3) NOT NULL,
	`lerwickTempC` INT (3) NOT NULL,
	`belfastTempC` INT (3) NOT NULL,
	`forecasterName` TEXT (20) NOT NULL,
	PRIMARY KEY(`forecastID`)
) TYPE = MYISAM COMMENT = 'UK Daily Forecast Table';