<?php
include("databaseConnect.php");

/** UPDATES UK DAILY FORECAST AND THE WEEKEND FORECAST **/
/**$query = "UPDATE ukdailyforecast SET forecastDate='$_POST[forecastDate]', issueDate='$_POST[issueDate]', issueMonth='$_POST[issueMonth]', issueYear='$_POST[issueYear]', issueTime='$_POST[issueTime]', headline='$_POST[headline]', synopsis='$_POST[synopsis]', maxTempC='$_POST[maxTempC]', minTempC='$_POST[minTempC]', pollen='$_POST[pollen]', uv='$_POST[uv]', scillyWeather='$_POST[scillyWeather]', scillyTempC='$_POST[scillyTempC]', plymouthWeather='$_POST[plymouthWeather]', plymouthTempC='$_POST[plymouthTempC]', southamptonWeather='$_POST[southamptonWeather]', southamptonTempC='$_POST[southamptonTempC]', londonWeather='$_POST[londonWeather]', londonTempC='$_POST[londonTempC]', norwichWeather='$_POST[norwichWeather]', norwichTempC='$_POST[norwichTempC]', birminghamWeather='$_POST[birminghamWeather]', birminghamTempC='$_POST[birminghamTempC]', aberystwythWeather='$_POST[aberystwythWeather]', aberystwythTempC='$_POST[aberystwythTempC]', manchesterWeather='$_POST[manchesterWeather]', manchesterTempC='$_POST[manchesterTempC]', yorkWeather='$_POST[yorkWeather]', yorkTempC='$_POST[yorkTempC]', newcastleWeather='$_POST[newcastleWeather]', newcastleTempC='$_POST[newcastleTempC]', isleOfManWeather='$_POST[isleOfManWeather]', isleOfManTempC='$_POST[isleOfManTempC]', carlisleWeather='$_POST[carlisleWeather]', carlisleTempC='$_POST[carlisleTempC]', edinburghWeather='$_POST[edinburghWeather]', edinburghTempC='$_POST[edinburghTempC]', glasgowWeather='$_POST[glasgowWeather]', glasgowTempC='$_POST[glasgowTempC]', aberdeenWeather='$_POST[aberdeenWeather]', aberdeenTempC='$_POST[aberdeenTempC]', invernessWeather='$_POST[invernessWeather]', invernessTempC='$_POST[invernessTempC]', stornowayWeather='$_POST[stornowayWeather]', stornowayTempC='$_POST[stornowayTempC]', lerwickWeather='$_POST[lerwickWeather]', lerwickTempC='$_POST[lerwickTempC]', belfastWeather='$_POST[belfastWeather]', belfastTempC='$_POST[belfastTempC]', forecasterName='$_POST[forecasterName]' WHERE forecastID='1'";**/
$query = "INSERT INTO ukdailyforecast (forecastDate, issueDate, issueMonth, issueYear, issueTime, headline, synopsis, maxTempC, minTempC, pollen, uv, scillyWeather, scillyTempC, plymouthWeather, plymouthTempC, southamptonWeather, southamptonTempC, londonWeather, londonTempC, norwichWeather, norwichTempC, birminghamWeather, birminghamTempC, aberystwythWeather, aberystwythTempC, manchesterWeather, manchesterTempC, yorkWeather, yorkTempC, newcastleWeather, newcastleTempC, isleOfManWeather, isleOfManTempC, carlisleWeather, carlisleTempC, edinburghWeather, edinburghTempC, glasgowWeather, glasgowTempC, aberdeenWeather, aberdeenTempC, invernessWeather, invernessTempC, stornowayWeather, stornowayTempC, lerwickWeather, lerwickTempC, belfastWeather, belfastTempC, forecasterName) VALUES ('$_POST[forecastDate]', '$_POST[issueDate]', '$_POST[issueMonth]', '$_POST[issueYear]', '$_POST[issueTime]', '$_POST[headline]', '$_POST[synopsis]', '$_POST[maxTempC]', '$_POST[minTempC]', '$_POST[pollen]', '$_POST[uv]', '$_POST[scillyWeather]', '$_POST[scillyTempC]', '$_POST[plymouthWeather]', '$_POST[plymouthTempC]', '$_POST[southamptonWeather]', '$_POST[southamptonTempC]', '$_POST[londonWeather]', '$_POST[londonTempC]', '$_POST[norwichWeather]', '$_POST[norwichTempC]', '$_POST[birminghamWeather]', '$_POST[birminghamTempC]', '$_POST[aberystwythWeather]', '$_POST[aberystwythTempC]', '$_POST[manchesterWeather]', '$_POST[manchesterTempC]', '$_POST[yorkWeather]', '$_POST[yorkTempC]', '$_POST[newcastleWeather]', '$_POST[newcastleTempC]', '$_POST[isleOfManWeather]', '$_POST[isleOfManTempC]', '$_POST[carlisleWeather]', '$_POST[carlisleTempC]', '$_POST[edinburghWeather]', '$_POST[edinburghTempC]', '$_POST[glasgowWeather]', '$_POST[glasgowTempC]', '$_POST[aberdeenWeather]', '$_POST[aberdeenTempC]', '$_POST[invernessWeather]', '$_POST[invernessTempC]', '$_POST[stornowayWeather]', '$_POST[stornowayTempC]', '$_POST[lerwickWeather]', '$_POST[lerwickTempC]', '$_POST[belfastWeather]', '$_POST[belfastTempC]', '$_POST[forecasterName]')";
$result = mysql_query($query);
if(!$result) {
	echo mysql_error();
	echo "<meta http-equiv='refresh' content='5;url=confirmation.php?message=failed'>";
}
else {
	echo "<meta http-equiv='refresh' content='0;url=confirmation.php?message=success'>";
}

?>